menu:
- {name: 'research', url: '/research'}
- {name: 'teaching', url: '/teaching'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}
- {name: 'other', url: '/other'}

social:
- {icon: 'github', link: 'https://github.com/haleyk'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/haley-keglovits/'}

contacts:
- {name: 'haley keglovits, phd', title: 'college fellow', department: 'psychological science', institution: 'harvard university', institution_address: 'cambridge, massachusetts', email: 'haleykegl [at] gmail [dot] com', office: 'william james hall floor 7', image: 'assets/img/haley.png'}
